import os

POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_HOST_AUTH_METHOD = os.getenv("POSTGRES_HOST_AUTH_METHOD")
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
AWS_SECRETS_MANAGER_NAME = os.getenv("AWS_SECRETS_MANAGER_NAME")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
